services:
    mysql:
        image: mysql:8
        container_name: event_project_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
            - ./u180743896_laravel.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
        ports:
            - "3310:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: event_project_phpmyadmin
        depends_on:
            - mysql
        ports:
            - "9001:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: "3306"

volumes:
    dbdata:
    storage: